/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tester_001;

import java.awt.Component;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableCellRenderer;
import javax.swing.table.TableColumn;

/**
 *
 * @author Jou
 */
public class NewJFrameListSampah extends javax.swing.JFrame {
    NewJFrameAdmin adm;
    NewJFrameMaster mst;
    ArrayList<Sampah> sampah;
    DefaultTableModel dt;
    class LabelRenderer implements TableCellRenderer{

        @Override
        public Component getTableCellRendererComponent(JTable jtable, Object o, boolean bln, boolean bln1, int i, int i1) {
            String photoname=o.toString();
            ImageIcon icon=new ImageIcon(photoname);
            TableColumn tc=TableSampah.getColumn("ICON");
            tc.setMinWidth(100);
            tc.setMaxWidth(100);
            TableSampah.setRowHeight(100);
            return new JLabel(icon);
        }
	
    }
    public NewJFrameListSampah() {
        initComponents();
    }
    public NewJFrameListSampah(NewJFrameMaster mastah,NewJFrameAdmin param) {
        initComponents();
        adm=param;
        mst=mastah;
        sampah=adm.arrsampah;
        refreshtable();
    }
    public void refreshtable(){
        sampah=adm.arrsampah;
        String[] row ={"KATEGORI","HARGA","ICON","KETERANGAN"};
        dt = new DefaultTableModel(row,0);
        for (Sampah s:sampah) {
            dt.addRow(s.getObj());
        }
        TableSampah.setDefaultEditor(Object.class, null);
        TableSampah.setModel(dt);
        TableColumn tc=TableSampah.getColumn("ICON");
        TableSampah.getColumnModel().getColumn(2).setCellRenderer(new LabelRenderer());
    }
//    public void loadTabel(){
//        arrHTrans = new ArrayList<>();
//        String [] row = {"TRANSACTION ID","CUSTOMER NAME","TRANSACTION DATE","SUBTOTAL"};
//        dt = new DefaultTableModel(row,0);
//        try {
//            statement = con.createStatement();
//            rs = statement.executeQuery("select * from htrans");
//            while(rs.next()){
//                HTrans ht = new HTrans(rs.getInt("IDTRANS"),
//                        rs.getString("CUSTOMER"),
//                        rs.getDate("WAKTUTRANSAKSI"),
//                        rs.getInt("TOTAL"));
//               arrHTrans.add(ht);
//            }
//            rs.close();
//        } catch (SQLException ex) {
//            Logger.getLogger(NewJFrame_transactionReport.class.getName()).log(Level.SEVERE, null, ex);
//        }
//        for(HTrans h : arrHTrans){
//            
//            if(jDateChooser4.getDate().getTime()<=h.getWaktutransaksi().getTime()&&jDateChooser3.getDate().getTime()>=h.getWaktutransaksi().getTime()){
//                dt.addRow(h.getObj());
//            }
//        }
//        jTable1.setDefaultEditor(Object.class, null);
//        jTable1.setModel(dt);
//        
//    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TableSampah = new javax.swing.JTable();
        logo = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        BackGround = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableSampah.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableSampah.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableSampahMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableSampah);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 241, 870, 275));

        logo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tester_001/kaumrombeng.png"))); // NOI18N
        getContentPane().add(logo, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        jLabel1.setText("LIST DATA SAMPAH");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(313, 195, -1, -1));

        BackGround.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tester_001/BackgroundSampah.jpg"))); // NOI18N
        getContentPane().add(BackGround, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        mst.status_list=false;
        dispose();
    }//GEN-LAST:event_formWindowClosing

    private void TableSampahMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableSampahMouseClicked

        int index=TableSampah.getSelectedRow();
        String kategori=sampah.get(index).getKategori();
        String keterangan=sampah.get(index).getKeterangan();
        int harga=sampah.get(index).getHarga();
        int id=sampah.get(index).getId();
        String passing=id+"~"+kategori+"~"+harga+"~"+keterangan;
        mst.RefreshTextField(mst, passing);
    }//GEN-LAST:event_TableSampahMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameListSampah.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameListSampah().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BackGround;
    private javax.swing.JTable TableSampah;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logo;
    // End of variables declaration//GEN-END:variables
}
