/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package tester_001;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;

/**
 *
 * @author ADMIN
 */


public class NewJFrame_transactionDetail extends javax.swing.JFrame {
    DefaultTableModel tm;
    ArrayList<DTrans> arr;
    int id;
    Connection con;
    Statement statement;
    PreparedStatement ps;
    ResultSet rs;
    DefaultTableModel dt;
    int index;
    int idtransaksi;
    int row, column;
    /**
     * Creates new form NewJFrame_transactionDetail
     */
    public NewJFrame_transactionDetail() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testingdbproyek","root","");
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame_transactionReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        jLabel_transactionID.setText(frmReport.idtransaksi+"");
        arr = new ArrayList<>();
        loadTabel();
    }
    
    NewJFrame_transactionReport frmReport;
    public NewJFrame_transactionDetail(NewJFrame_transactionReport param) {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/testingdbproyek","root","");
        } catch (Exception ex) {
            Logger.getLogger(NewJFrame_transactionReport.class.getName()).log(Level.SEVERE, null, ex);
        }
        initComponents();
        frmReport = param;
        jLabel_transactionID.setText(frmReport.idtransaksi+"");
        arr = new ArrayList<>();
        loadTabel();
    }
    
    public void loadTabel(){
        String[] title ={"CATEGORY","PRICE", "WEIGHT","SUBTOTAL"};
        tm = new DefaultTableModel(title,0);
        jTable2.setModel(tm);
        jTable2.setDefaultEditor(Object.class, null);
        try {
            
            ps = con.prepareStatement("SELECT * FROM DTRANS WHERE IDHTRANS=?");
            ps.setInt(1,frmReport.idtransaksi);
            rs = ps.executeQuery();
            while (rs.next()) {                
                DTrans dtranss = new DTrans(rs.getString("KATEGORY"),
                    rs.getInt("HARGA"),
                    rs.getInt("BERAT"),
		    rs.getInt("HARGA")*rs.getInt("BERAT"));
                arr.add(dtranss);
            }
            rs.close();
        } catch (Exception e) {
            Logger.getLogger(NewJFrame_transactionDetail.class.getName()).log(Level.SEVERE, null, e);
        }
        
        for(DTrans d : arr){
            
            tm.addRow(d.getObj());
            System.out.println(d.getObj());
        }
        jTable2.setDefaultEditor(Object.class, null);
        jTable2.setModel(tm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel8 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel_transactionID = new javax.swing.JLabel();
        jButton_saveDetails = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(null);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTable2);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(50, 260, 710, 180);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 31)); // NOI18N
        jLabel8.setText("TRANSACTION DETAILS");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(400, 140, 410, 80);

        jLabel1.setText("TRANSACTION ID : ");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(460, 220, 96, 14);

        jLabel_transactionID.setText("jLabel_transactionID");
        getContentPane().add(jLabel_transactionID);
        jLabel_transactionID.setBounds(590, 220, 209, 14);

        jButton_saveDetails.setText("SAVE DETAILS");
        jButton_saveDetails.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_saveDetailsMouseClicked(evt);
            }
        });
        getContentPane().add(jButton_saveDetails);
        jButton_saveDetails.setBounds(50, 460, 101, 23);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tester_001/search.png"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(650, 0, 160, 150);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tester_001/Background_Det.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 800, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents
public void writeFile(File f){
        try {
            FileWriter fw = new FileWriter(f);
            BufferedWriter writer = new BufferedWriter(fw);
            writer.write("TRANSACTION DETAILS");
            writer.newLine();
            writer.newLine();
            writer.write("TRANSACTION ID : " + frmReport.idtransaksi);
            writer.newLine();
            writer.write("CATEGORY~PRICE~WEIGHT~SUBTOTAL");
            writer.newLine();
            for(DTrans dt :arr){
                writer.write(dt.toString());
                writer.newLine();
            }
            //HARUS URUT
            writer.close();
            fw.close();
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    private void jButton_saveDetailsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_saveDetailsMouseClicked
        // TODO add your handling code here:
        jFileChooser1.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int response = jFileChooser1.showSaveDialog(this);
        if(response == JFileChooser.APPROVE_OPTION){
            File selectedFile = jFileChooser1.getSelectedFile();
            writeFile(selectedFile);
        }
    }//GEN-LAST:event_jButton_saveDetailsMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_transactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_transactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_transactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame_transactionDetail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame_transactionDetail().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_saveDetails;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel_transactionID;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables
}
